---

- name: Setup provider
  set_fact:
    provider:
      server: "{{ provider_server }}"
      server_port: "{{ provider_server_port }}"
      user: "{{ provider_user }}"
      password: "{{ provider_password }}"
      validate_certs: "{{ provider_validate_certs }}"
      transport: "{{ provider_transport }}"

- name: Wait for BIG-IP to be available
  bigip_wait:
    timeout: 300
    provider: "{{ provider }}"
  delegate_to: localhost
  register: status
  until: status is success
  retries: 10
  delay: 6

- name: License the device
  bigip_device_license:
    license_key: "{{ bigip_onboard_license }}"
    provider: "{{ provider }}"
  delegate_to: localhost
  when: bigip_onboard_license is defined and bigip_onboard_license != ''

- name: Configure NTP server on BIG-IP
  bigip_device_ntp:
    provider: "{{ provider }}"
    ntp_servers: "{{ bigip_onboard_ntp_servers }}"
  delegate_to: localhost

- name: Configure BIG-IP hostname
  bigip_hostname:
    provider: "{{ provider }}"
    hostname: "{{ bigip_onboard_hostname }}"
  delegate_to: localhost
  when: bigip_onboard_hostname is defined and bigip_onboard_hostname != ""

- name: Manage SSHD setting on BIG-IP
  bigip_device_sshd:
    provider: "{{ provider }}"
    banner: enabled
    banner_text: " {{ bigip_onboard_banner_text|default(omit) }}"
  delegate_to: localhost

- name: Manage BIG-IP DNS settings
  bigip_device_dns:
    provider: "{{ provider }}"
    name_servers: "{{ bigip_onboard_dns_servers|default(omit) }}"
    search: "{{ bigip_onboard_dns_search_domains|default(omit) }}"
    ip_version: "{{ bigip_onboard_dns_ip_version|default(omit) }}"
  delegate_to: localhost

- name: Provision BIG-IP with appropriate modules
  bigip_provision:
    provider: "{{ provider }}"
    module: "{{ item.name }}"
    level: "{{ item.level|default(omit) }}"
  loop: "{{ bigip_onboard_module_provisioning }}"
  when: bigip_onboard_module_provisioning is defined and bigip_onboard_module_provisioning != ""
  delegate_to: localhost

- name: Configure VLANs on the BIG-IP
  bigip_vlan:
    provider: "{{ provider }}"
    name: "{{ item.name }}"
    tag: "{{ item.tag|default(omit) }}"
    tagged_interface: "{{ item.interface|default(omit) }}"
  loop: "{{ bigip_onboard_vlan_information }}"
  delegate_to: localhost

- name: Configure SELF-IPs on the BIG-IP
  bigip_selfip:
    provider: "{{ provider }}"
    name: "{{ item.name }}"
    address: "{{ item.address }}"
    netmask: "{{ item.netmask }}"
    vlan: "{{ item.vlan }}"
    allow_service: "{{ item.allow_service|default(omit) }}"
  loop: "{{ bigip_onboard_selfip_information }}"
  delegate_to: localhost

- name: Disable the setup utility
  bigip_sys_global:
    provider: "{{ provider }}"
    gui_setup: no
  delegate_to: localhost
